---
title: "Compas Marital Status"
authors: Roberto Balderas and Ernesto Delamaza
output: html_document
date: '2022-06-14'
---

```{r setup, include=FALSE}
# load libraries
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(effects)
```

### Roberto Balderas and Ernesto Delamaza

***

The data we will use for the visualizations https://raw.githubusercontent.com/propublica/compas-analysis/master/compas-scores-raw.csv

***

```{r}
# read data in
compas_data <- read_csv("raw-data/compas-scores-raw.csv")

# filter data
fta_data <- compas_data %>% 
  filter(DisplayText == "Risk of Failure to Appear")

fta_data %>% 
  distinct(MaritalStatus)

# fix categorical variables
fta_data <- fta_data %>%
  mutate(race_ethnicity = case_when(Ethnic_Code_Text == "Caucasian" ~ "White",
                                    Ethnic_Code_Text == "African-Am" ~ "African American",
                                    Ethnic_Code_Text == "Oriental" ~ "Asian",
                                    TRUE ~ Ethnic_Code_Text))

fta_data %>% 
  distinct(Ethnic_Code_Text, race_ethnicity)
```
```{r}
# create linear regression model
marital_sex_model <- lm(DecileScore ~ MaritalStatus + Sex_Code_Text,
                        data = fta_data)

# summary of the model
summary(marital_sex_model)

# assign model data to a dataframe
sex_model_df <- effect("MaritalStatus", marital_sex_model) %>% 
  data.frame()

sex_model_df
```
```{r}
# count occurrences of each marital status
marital_status_failure_to_appear <- fta_data %>%
  count(MaritalStatus)

# change column name
colnames(marital_status_failure_to_appear)[colnames(marital_status_failure_to_appear) == "n"] <- "Occurrences"

```

```{r}
# create a bar plot
marital_status_failure_to_appear %>% 
  ggplot(aes(y = reorder(MaritalStatus, Occurrences),
             x = Occurrences)) +
  geom_col() +
  geom_label(aes(label = Occurrences)) +
  labs(y = "Marital Status",
       title = "Occurrences of Failure to Appear Based on Marital Status",
       caption = "data from www.propublica.org")

```

```{r}
# plot the linear regression model
sex_model_df %>% 
  ggplot(aes(y = reorder(MaritalStatus, fit),
             x = fit,
             xmin = lower,
             xmax = upper)) +
  geom_errorbar() +
  geom_label(aes(label = format(fit, digits = 2))) +
  labs(y = "Marital Status",
       x = "average decile score for risk of failure to appear (1-10)",
       caption = "data from www.propublica.org")
```

```{r}
# save processed data to csv
write_csv(fta_data, "processed-data/fta-marital-data.csv")
```


